-- packages/ref-currency/sql/common/ref-currency-data.sql
--
-- @author jon@jongriffin.com
-- @creation-date 2001-
-- @cvs-id $Id$

-- initial data for currencies

-- set feedback off;

insert into currencies values ('NA',NULL,' ',NULL,'No universal currency');
insert into currencies values ('ADP','20','0',NULL,'Andorran Peseta');
insert into currencies values ('AED','784','2',NULL,'UAE Dirham');
insert into currencies values ('AFA','4','2',NULL,'Afghani');
insert into currencies values ('ALL','8','2',NULL,'Lek');
insert into currencies values ('AMD','51','2',NULL,'Armenian Dram');
insert into currencies values ('ANG','532','2',NULL,'Netherlands Antillan Guilder');
insert into currencies values ('AOA','973','2',NULL,'Kwanza');
insert into currencies values ('ARS','32','2',NULL,'Argentine Peso');
insert into currencies values ('ATS','40','2',NULL,'Schilling');
insert into currencies values ('AUD','36','2',NULL,'Australian Dollar');
insert into currencies values ('AWG','533','2',NULL,'Aruban Guilder');
insert into currencies values ('AZM','31','2',NULL,'Azerbaijanian Manat');
insert into currencies values ('BAM','977','2',NULL,'Convertible Marks');
insert into currencies values ('BBD','52','2',NULL,'Barbados Dollar');
insert into currencies values ('BDT','50','2',NULL,'Taka');
insert into currencies values ('BEF','56','0',NULL,'Belgian Franc');
insert into currencies values ('BGL','100','2',NULL,'Lev');
insert into currencies values ('BGN','975','2',NULL,'Bulgarian Lev');
insert into currencies values ('BHD','48','3',NULL,'Bahraini Dinar');
insert into currencies values ('BIF','108','0',NULL,'Burundi Franc');
insert into currencies values ('BMD','60','2',NULL,'Bermudian Dollar');
insert into currencies values ('BND','96','2',NULL,'Brunei Dollar');
insert into currencies values ('BOB','68','2',NULL,'Boliviano');
insert into currencies values ('BOV','984','2',NULL,'Mvdol');
insert into currencies values ('BRL','986','2',NULL,'Brazilian Real');
insert into currencies values ('BSD','44','2',NULL,'Bahamian Dollar');
insert into currencies values ('BTN','64','2',NULL,'Ngultrum');
insert into currencies values ('BWP','72','2',NULL,'Pula');
insert into currencies values ('BYB','112','0',NULL,'Belarussian Ruble');
insert into currencies values ('BYR','974','0',NULL,'Belarussian Ruble');
insert into currencies values ('BZD','84','2',NULL,'Belize Dollar');
insert into currencies values ('CAD','124','2',NULL,'Canadian Dollar');
insert into currencies values ('CDF','976','2',NULL,'Franc Congolais');
insert into currencies values ('CHF','756','2',NULL,'Swiss Franc');
insert into currencies values ('CLF','990','0',NULL,'Unidades de fomento');
insert into currencies values ('CLP','152','0',NULL,'Chilean Peso');
insert into currencies values ('CNY','156','2',NULL,'Yuan Renminbi');
insert into currencies values ('COP','170','2',NULL,'Colombian Peso');
insert into currencies values ('CRC','188','2',NULL,'Costa Rican Colon');
insert into currencies values ('CUP','192','2',NULL,'Cuban Peso');
insert into currencies values ('CVE','132','2',NULL,'Cape Verde Escudo');
insert into currencies values ('CYP','196','2',NULL,'Cyprus Pound');
insert into currencies values ('CZK','203','2',NULL,'Czech Koruna');
insert into currencies values ('DEM','276','2',NULL,'Deutsche Mark');
insert into currencies values ('DJF','262','0',NULL,'Djibouti Franc');
insert into currencies values ('DKK','208','2',NULL,'Danish Krone');
insert into currencies values ('DOP','214','2',NULL,'Dominican Peso');
insert into currencies values ('DZD','12','2',NULL,'Algerian Dinar');
insert into currencies values ('EEK','233','2',NULL,'Kroon');
insert into currencies values ('EGP','818','2',NULL,'Egyptian Pound');
insert into currencies values ('ERN','232','2',NULL,'Nakfa');
insert into currencies values ('ESP','724','0',NULL,'Spanish Peseta');
insert into currencies values ('ETB','230','2',NULL,'Ethiopian Birr');
insert into currencies values ('FIM','246','2',NULL,'Markka');
insert into currencies values ('FJD','242','2',NULL,'Fiji Dollar');
insert into currencies values ('FKP','238','2',NULL,'Falkland Islands Pound');
insert into currencies values ('FRF','250','2',NULL,'French Franc');
insert into currencies values ('GBP','826','2',NULL,'Pound Sterling');
insert into currencies values ('GEL','981','2',NULL,'Lari');
insert into currencies values ('GHC','288','2',NULL,'Cedi');
insert into currencies values ('GIP','292','2',NULL,'Gibraltar Pound');
insert into currencies values ('GMD','270','2',NULL,'Dalasi');
insert into currencies values ('GNF','324','0',NULL,'Guinea Franc');
insert into currencies values ('GRD','300','0',NULL,'Drachma');
insert into currencies values ('GTQ','320','2',NULL,'Quetzal');
insert into currencies values ('GWP','624','2',NULL,'Guinea-Bissau Peso');
insert into currencies values ('GYD','328','2',NULL,'Guyana Dollar');
insert into currencies values ('HKD','344','2',NULL,'Hong Kong Dollar');
insert into currencies values ('HNL','340','2',NULL,'Lempira');
insert into currencies values ('HRK','191','2',NULL,'Croatian kuna');
insert into currencies values ('HTG','332','2',NULL,'Gourde');
insert into currencies values ('HUF','348','2',NULL,'Forint');
insert into currencies values ('IDR','360','2',NULL,'Rupiah');
insert into currencies values ('IEP','372','2',NULL,'Irish Pound');
insert into currencies values ('ILS','376','2',NULL,'New Israeli Sheqel');
insert into currencies values ('INR','356','2',NULL,'Indian Rupee');
insert into currencies values ('IQD','368','3',NULL,'Iraqi Dinar');
insert into currencies values ('IRR','364','2',NULL,'Iranian Rial');
insert into currencies values ('ISK','352','2',NULL,'Iceland Krona');
insert into currencies values ('ITL','380','0',NULL,'Italian Lira');
insert into currencies values ('JMD','388','2',NULL,'Jamaican Dollar');
insert into currencies values ('JOD','400','3',NULL,'Jordanian Dinar');
insert into currencies values ('JPY','392','0',NULL,'Yen');
insert into currencies values ('KES','404','2',NULL,'Kenyan Shilling');
insert into currencies values ('KGS','417','2',NULL,'Som');
insert into currencies values ('KHR','116','2',NULL,'Riel');
insert into currencies values ('KMF','174','0',NULL,'Comoro Franc');
insert into currencies values ('KPW','408','2',NULL,'North Korean Won');
insert into currencies values ('KRW','410','0',NULL,'Won');
insert into currencies values ('KWD','414','3',NULL,'Kuwaiti Dinar');
insert into currencies values ('KYD','136','2',NULL,'Cayman Islands Dollar');
insert into currencies values ('KZT','398','2',NULL,'Tenge');
insert into currencies values ('LAK','418','2',NULL,'Kip');
insert into currencies values ('LBP','422','2',NULL,'Lebanese Pound');
insert into currencies values ('LKR','144','2',NULL,'Sri Lanka Rupee');
insert into currencies values ('LRD','430','2',NULL,'Liberian Dollar');
insert into currencies values ('LSL','426','2',NULL,'Loti');
insert into currencies values ('LTL','440','2',NULL,'Lithuanian Litus');
insert into currencies values ('LUF','442','0',NULL,'Luxembourg Franc');
insert into currencies values ('LVL','428','2',NULL,'Latvian Lats');
insert into currencies values ('LYD','434','3',NULL,'Lybian Dinar');
insert into currencies values ('MAD','504','2',NULL,'Moroccan Dirham');
insert into currencies values ('MDL','498','2',NULL,'Moldovan Leu');
insert into currencies values ('MGF','450','0',NULL,'Malagasy Franc');
insert into currencies values ('MKD','807','2',NULL,'Denar');
insert into currencies values ('MMK','104','2',NULL,'Kyat');
insert into currencies values ('MNT','496','2',NULL,'Tugrik');
insert into currencies values ('MOP','446','2',NULL,'Pataca');
insert into currencies values ('MRO','478','2',NULL,'Ouguiya');
insert into currencies values ('MTL','470','2',NULL,'Maltese Lira');
insert into currencies values ('MUR','480','2',NULL,'Mauritius Rupee');
insert into currencies values ('MVR','462','2',NULL,'Rufiyaa');
insert into currencies values ('MWK','454','2',NULL,'Kwacha');
insert into currencies values ('MXN','484','2',NULL,'Mexican Peso');
insert into currencies values ('MXV','979','2',NULL,'Mexican Unidad de Inversion (UDI)');
insert into currencies values ('MYR','458','2',NULL,'Malaysian Ringgit');
insert into currencies values ('MZM','508','2',NULL,'Metical');
insert into currencies values ('NAD','516','2',NULL,'Namibia Dollar');
insert into currencies values ('NGN','566','2',NULL,'Naira');
insert into currencies values ('NIO','558','2',NULL,'Cordoba Oro');
insert into currencies values ('NLG','528','2',NULL,'Netherlands Guilder');
insert into currencies values ('NOK','578','2',NULL,'Norvegian Krone');
insert into currencies values ('NPR','524','2',NULL,'Nepalese Rupee');
insert into currencies values ('NZD','554','2',NULL,'New Zealand Dollar');
insert into currencies values ('OMR','512','3',NULL,'Rial Omani');
insert into currencies values ('PAB','590','2',NULL,'Balboa');
insert into currencies values ('PEN','604','2',NULL,'Nuevo Sol');
insert into currencies values ('PGK','598','2',NULL,'Kina');
insert into currencies values ('PHP','608','2',NULL,'Philippine Peso');
insert into currencies values ('PKR','586','2',NULL,'Pakistan Rupee');
insert into currencies values ('PLN','985','2',NULL,'Zloty');
insert into currencies values ('PTE','620','0',NULL,'Portuguese Escudo');
insert into currencies values ('PYG','600','0',NULL,'Guarani');
insert into currencies values ('QAR','634','2',NULL,'Qatari Rial');
insert into currencies values ('ROL','642','2',NULL,'Leu');
insert into currencies values ('RUB','643','2',NULL,'Russian Ruble');
insert into currencies values ('RUR','810','2',NULL,'Russian Ruble');
insert into currencies values ('RWF','646','0',NULL,'Rwanda Franc');
insert into currencies values ('SAR','682','2',NULL,'Saudi Riyal');
insert into currencies values ('SBD','90','2',NULL,'Solomon Islands Dollar');
insert into currencies values ('SCR','690','2',NULL,'Seychelles Rupee');
insert into currencies values ('SDD','736','2',NULL,'Sudanese Dinar');
insert into currencies values ('SEK','752','2',NULL,'Swedish Krona');
insert into currencies values ('SGD','702','2',NULL,'Singapore Dollar');
insert into currencies values ('SHP','654','2',NULL,'Saint Helena Pound');
insert into currencies values ('SIT','705','2',NULL,'Tolar');
insert into currencies values ('SKK','703','2',NULL,'Slovak Koruna');
insert into currencies values ('SLL','694','2',NULL,'Leone');
insert into currencies values ('SOS','706','2',NULL,'Somali Shilling');
insert into currencies values ('SRG','740','2',NULL,'Suriname Guilder');
insert into currencies values ('STD','678','2',NULL,'Dobra');
insert into currencies values ('SVC','222','2',NULL,'El Salvador Colon');
insert into currencies values ('SYP','760','2',NULL,'Syrian Pound');
insert into currencies values ('SZL','748','2',NULL,'Lilangeni');
insert into currencies values ('THB','764','2',NULL,'Baht');
insert into currencies values ('TJR','762','0',NULL,'Tajik Ruble');
insert into currencies values ('TJS','972','0',NULL,'Somoni');
insert into currencies values ('TMM','795','2',NULL,'Manat');
insert into currencies values ('TND','788','3',NULL,'Tunisian Dinar');
insert into currencies values ('TOP','776','2',NULL,'Paaaaanga');
insert into currencies values ('TPE','626','0',NULL,'Timor Escudo');
insert into currencies values ('TRL','792','0',NULL,'Turkish Lira');
insert into currencies values ('TTD','780','2',NULL,'Trinidad and Tobago Dollar');
insert into currencies values ('TWD','901','2',NULL,'New Taiwan Dollar');
insert into currencies values ('TZS','834','2',NULL,'Tanzanian Shilling');
insert into currencies values ('UAH','980','2',NULL,'Hryvnia');
insert into currencies values ('UGX','800','2',NULL,'Uganda Shilling');
insert into currencies values ('USD','840','2',NULL,'US Dollar');
insert into currencies values ('USN','997','2',NULL,'US Dollar (Next day)');
insert into currencies values ('USS','998','2',NULL,'US Dollar (Same day)');
insert into currencies values ('UYU','858','2',NULL,'Peso Uruguayo');
insert into currencies values ('UZS','860','2',NULL,'Uzbekistan Sum');
insert into currencies values ('VEB','862','2',NULL,'Bolivar');
insert into currencies values ('VND','704','2',NULL,'Dong');
insert into currencies values ('VUV','548','0',NULL,'Vatu');
insert into currencies values ('WST','882','2',NULL,'Tala');
insert into currencies values ('XAF','950','0',NULL,'CFA Franc BEAC');
insert into currencies values ('XCD','951','2',NULL,'East Carribbean Dollar');
insert into currencies values ('XOF','952','0',NULL,'CFA Franc BCEAO');
insert into currencies values ('XPF','953','0',NULL,'CFP Franc');
insert into currencies values ('YER','886','2',NULL,'Yemeni Rial');
insert into currencies values ('YUM','891','2',NULL,'Yugoslavian Dinar');
insert into currencies values ('ZAR','710','2',NULL,'Rand');
insert into currencies values ('ZMK','894','2',NULL,'Kwacha');
insert into currencies values ('ZWD','716','2',NULL,'Zimbabwe Dollar');

-- set feedback on;
commit;






